sudo: required
services:
  - docker

before_install:
  - docker build -t mcparfer/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true mcparfer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-123989135412"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"